use itertools::Itertools;
use sqlx::database::HasArguments;
use sqlx::postgres::PgRow;
use sqlx::query::Query;
use sqlx::{Executor, FromRow, Postgres};

use super::selection::WithCount;
use super::*;
use crate::result::{Result, SharedDbError};

use std::fmt::Debug;

pub const MAX_BINDINGS: usize = u16::MAX as usize;
/// If we use UNNEST queries on very large datasets, postgres
/// will use a very large amount of RAM, which is unacceptable.
pub const UPDATE_UNNEST_VALUES: usize = 1_000_000;
const RETURNING: &str = " returning *";

/// This is part of the mechanism for simple return.
#[derive(Debug)]
pub enum ReturningEither<T: DbItem> {
    RowsAffected(u64),
    Items(Vec<T>),
}

impl<T: DbItem> ReturningEither<T> {
    pub fn new(returning: bool) -> Self {
        match returning {
            false => Self::RowsAffected(0),
            true => Self::Items(Vec::<T>::with_capacity(0)),
        }
    }
}

/// Paginaged response from DB.
pub struct Paginated<T> {
    /// Chunk of items.
    pub items: Vec<T>,
    /// Optional total count of items, as if returned without pagination.
    pub total: Option<i64>,
}

pub type BindQuery<'a> =
    Query<'a, Postgres, <Postgres as HasArguments<'a>>::Arguments>;

#[async_trait::async_trait]
/// This is a boiler plate trait that automatically implements utility functions to insert, update
/// and fetch items that implement it from a Postgres database via sqlx.
///
/// Currently the `db_item!` macro automatically creates the structure and implements the
/// required functions of the trait for you, although in future it may be changed to become
/// a proc macro.
///
/// NB: The `Unpin` bound is needed to be able to use `Query::map` in selection (and in general).
pub trait DbItem:
    FieldTolerance
    + for<'d> sqlx::FromRow<'d, PgRow>
    + Debug
    + Clone
    + Send
    + Sync
    + Unpin
{
    /// Each type of item has a table that it belongs to.
    const TABLE: &'static str;
    /// NB: A table can have multiple keys, eg (id_field, other_id_field)
    const PRIMARY_KEYS: &'static [&'static str];
    /// This constant contains row names where this item belongs.
    const FIELDS: &'static [&'static str];
    /// Indices of fields in [Self::FIELDS] that are primary keys of the table.
    const PRIMARY_KEY_INDICES: &'static [usize];
    /// This constant contains fields that are not automatically generated and is used for
    /// inserting a new structure into the DB.
    const INSERT_FIELDS: &'static [&'static str];
    /// This constant includes only fields that can be updated.
    const UPDATE_FIELDS: &'static [&'static str];
    /// Indices of fields in [Self::FIELDS] that shouldn't be updated
    /// (currently, fields that have `GENERATED ALWAYS AS ...` SQL constraint).
    const NO_UPDATE_INDICES: &'static [usize];

    /// Get the structure's primary key. Since the key can come as a flavour of integer,
    /// or as a string, we try to be value here.
    /// Since tables may change over time, we try to be flexible.
    /// This converts the structure into fields and binds to a query.
    fn bind_pkeys<'a>(&'a self, query: BindQuery<'a>) -> BindQuery<'a>;

    /// This converts the structure into fields and binds to a query. If autogenerated fields
    /// are present it is recommended to call `bind_to_query_insert` and then add extra fields.
    fn bind_to_query<'a>(&'a self, query: BindQuery<'a>) -> BindQuery<'a>;

    /// This converts the structure into fields and binds to a query, however it
    /// does not bind autogen fields.
    fn bind_to_query_insert<'a>(&'a self, query: BindQuery<'a>) -> BindQuery<'a>;

    /// Bind only fields that are specified. This is useful when updating a limited
    /// number of fields in a large table. This function should be used with care.
    fn bind_limited_fields<'a>(
        &'a self,
        query: BindQuery<'a>,
        mask: &DbFieldMask<Self>,
    ) -> BindQuery<'a>;

    /// Sometimes an item may have fields with information that is invalid for certain
    /// DB operations but not others. In that case those fields need to be activated
    /// with some values beforehand. Generally default values. This function exists
    /// in order to do so.
    fn activate_fields(&mut self);

    /// Converts the fields array into an array ready for insertion
    /// eg `["id", "name", "address"] becomes `"id,name,address"`.
    /// This method is provided.
    /// TODO: Convert into proc macro.
    fn fields_string() -> String {
        Self::FIELDS.join(",")
    }

    /// As `DbItem::fields_string` but for inserted fields only.
    fn insert_fields_string() -> String {
        Self::INSERT_FIELDS.join(",")
    }

    /// Converts the field array into a representation of the bindings.
    ///
    /// The `nth` argument tells us which item this is in the list that the counter may
    /// be adjusted correctly.
    /// eg `["id", "name", "address"] becomes `"($1,$2,$3)"`.
    /// TODO: Convert into a proc macro.
    fn field_counter(nth: usize) -> String {
        field_counter(Self::FIELDS, nth)
    }

    /// Count only the fields that are normally inserted (not for use with update or query)
    /// This needs to be different from `field_counter` only if there are autogenerated fields
    /// which are not usually inserted, but whose values are created/incremented by the DB.
    fn insert_field_counter(nth: usize) -> String {
        field_counter(Self::INSERT_FIELDS, nth)
    }

    /// This inserts an item into its table.
    ///
    /// It is assumed that the primary key is generated on the
    /// FRONTEND, which is incorrect. The internal implementation can be changed to NOT
    /// insert the primary key if it is `None`/`Default::default()` on the item being
    /// inserted without affecting the API.
    async fn insert<'a, Ex>(&mut self, pool: Ex) -> Result<u64>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        match self.insert_inner(pool, false).await? {
            ReturningEither::RowsAffected(x) => Ok(x),
            _ => panic!("Only returns rows."),
        }
    }

    /// This inserts an item into its table returning the inserted row. (See [`DbItem::insert`])
    async fn insert_returning<'a, Ex>(&mut self, pool: Ex) -> Result<Self>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        match self.insert_inner(pool, true).await? {
            ReturningEither::Items(mut x) => x.pop().ok_or_else(|| {
                SharedDbError::Other("insert_returning returned nothing".into())
            }),
            _ => panic!("Only returns items."),
        }
    }

    async fn insert_inner<'a, Ex>(
        &mut self,
        pool: Ex,
        returning: bool,
    ) -> Result<ReturningEither<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        self.activate_fields();
        let f = format!(
            "INSERT INTO {table} ({fields}) values{field_count}{ret_clause};",
            table = Self::TABLE,
            fields = Self::insert_fields_string(),
            field_count = Self::insert_field_counter(0),
            ret_clause = if returning { RETURNING } else { "" },
        );
        let q = sqlx::query(&f);

        if returning {
            let r = self
                .bind_to_query_insert(q)
                .try_map(|x| Self::from_row(&x))
                .fetch_all(pool)
                .await?;
            Ok(ReturningEither::Items(r))
        } else {
            let r = self
                .bind_to_query_insert(q)
                .execute(pool)
                .await
                .map(|r| r.rows_affected())?;
            Ok(ReturningEither::RowsAffected(r))
        }
    }

    /// Update a single value based on primary key.
    ///
    /// The argument `update_fields` contains the fields to be updated.
    /// If `update_fields` is none, then all fields will be updated.
    async fn update<'a, Ex>(
        &self,
        update_fields: Option<&[&str]>,
        pool: Ex,
    ) -> Result<u64>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        match self.update_inner(update_fields, None, pool).await? {
            ReturningEither::RowsAffected(x) => Ok(x),
            _ => unreachable!("Only returns rows."),
        }
    }

    /// Update a single value based on primary key.
    ///
    /// The argument `update_fields` contains the field mask.
    async fn update_masked<'a, Ex>(
        &self,
        update_fields: DbFieldMask<Self>,
        pool: Ex,
    ) -> Result<u64>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        match self.update_inner_masked(update_fields, None, pool).await? {
            ReturningEither::RowsAffected(x) => Ok(x),
            _ => unreachable!("Only returns rows."),
        }
    }

    /// Update a single value based on primary key. Unlike update it returns the
    /// updated item with the fields listed in `returning_fields`.
    ///
    /// NB: If the item has fields with `#[item_field_require_from_row]` attribute then
    /// `return_fields` must contain these fields, otherwise this will fail.
    async fn update_returning<'a, Ex, D: std::fmt::Display + Send + Sync>(
        &self,
        update_fields: Option<&[&str]>,
        return_fields: Option<&[D]>,
        pool: Ex,
    ) -> Result<Self>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        // Since the types D and &str are not "the same"...
        let return_fields = return_fields
            .map(|x| x.iter().map(|x| x.to_string()).collect::<Vec<_>>());
        let ret_fields = match return_fields {
            Some(ref f) => f.iter().map(|x| x as &str).collect::<Vec<_>>(),
            None => Self::FIELDS.to_vec(),
        };

        match self.update_inner(update_fields, Some(&ret_fields), pool).await? {
            ReturningEither::Items(mut x) => x.pop().ok_or_else(|| {
                SharedDbError::Other("update_returning returned nothing".into())
            }),
            _ => unreachable!("Only returns items."),
        }
    }

    async fn update_inner<'a, Ex>(
        &self,
        update_fields: Option<&[&str]>,
        return_fields: Option<&[&str]>,
        pool: Ex,
    ) -> Result<ReturningEither<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        // It is preferable to only update selected fields, but all data in these fields
        // must be valid.
        let update_fields = update_fields.map(Self::apply_tolerance_to_fields);
        let return_fields = return_fields.map(Self::apply_tolerance_to_fields);

        let update_mask = update_fields
            .as_ref()
            .map(|x| make_single_update_bind_mask::<Self>(x))
            .unwrap_or_else(|| make_bind_mask::<Self>(Self::UPDATE_FIELDS));

        let return_mask = return_fields.map(|x| make_bind_mask::<Self>(&x));

        self.update_inner_masked(update_mask, return_mask, pool).await
    }

    async fn update_inner_masked<'a, Ex>(
        &self,
        update_fields: DbFieldMask<Self>,
        return_fields: Option<DbFieldMask<Self>>,
        pool: Ex,
    ) -> Result<ReturningEither<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        use ReturningEither::*;
        // Define selected fields. We use the bind mask because it has some inbuilt
        // guarantees.
        let selected_fields = update_fields_helper::<Self>(&update_fields);
        let field_count = field_counter(&selected_fields, 0);

        // NB: This is very definitely optional.
        let return_clause = return_fields
            .map(|x| {
                let fields = select_fields_helper::<Self>(&x);
                format!(" RETURNING {}", fields.join(","))
            })
            .unwrap_or_default();

        let fields = selected_fields.join(",");

        let field_thread = if selected_fields.len() == 1 {
            format!("{}={}", fields, field_count)
        } else {
            format!("({})=({})", fields, field_count)
        };

        let where_clause = Self::PRIMARY_KEYS
            .iter()
            .enumerate()
            .map(|(i, k)| {
                format!("{k}=${n}", k = k, n = i + 1 + selected_fields.len())
            })
            .collect::<Vec<_>>()
            .join(" AND ");

        let f = format!(
            "UPDATE {table} set {field_thread} WHERE {where_clause}{returning};",
            table = Self::TABLE,
            field_thread = field_thread,
            where_clause = where_clause,
            returning = return_clause,
        );
        let mut q = sqlx::query(&f);
        q = self.bind_limited_fields(q, &update_fields);
        q = self.bind_pkeys(q);

        let ret = match return_clause.is_empty() {
            true => RowsAffected(q.execute(pool).await?.rows_affected()),
            false => {
                let x = q.try_map(|r| Self::from_row(&r)).fetch_all(pool).await?;
                Items(x)
            }
        };
        Ok(ret)
    }

    /// Inserts a vec of items into the table.
    ///
    /// The approach of using a borrowed slice instead of an iterator is used,
    /// because it allows a little bit more flexibility for the caller.
    /// It is assumed that the performance cost of the DB call eclipses the cost
    /// of holding the slice.
    ///
    /// NB: If `DbItem` is derived automatically, the derived `insert_vec` function
    ///     differs from the default.
    async fn insert_vec(
        items: &mut [Self],
        pool: &mut sqlx::Transaction<Postgres>,
    ) -> Result<u64> {
        match Self::insert_vec_inner(items, pool, false).await? {
            ReturningEither::RowsAffected(x) => Ok(x),
            _ => panic!("Only returns rows."),
        }
    }

    /// Inserts a vec of items into the table returning the inserted rows. (See [`DbItem::insert_vec`])
    async fn insert_vec_returning(
        items: &mut [Self],
        pool: &mut sqlx::Transaction<Postgres>,
    ) -> Result<Vec<Self>> {
        match Self::insert_vec_inner(items, pool, true).await? {
            ReturningEither::Items(x) => Ok(x),
            _ => panic!("Only returns items."),
        }
    }

    async fn insert_vec_inner(
        items: &mut [Self],
        pool: &mut sqlx::Transaction<Postgres>,
        returning: bool,
    ) -> Result<ReturningEither<Self>> {
        let mut ret = ReturningEither::<Self>::new(returning);
        if items.is_empty() {
            return Ok(ret);
        }
        let fields = Self::insert_fields_string();

        for items in items.chunks_mut(MAX_BINDINGS / fields.len()) {
            let mut query_string = format!(
                "INSERT INTO {table} ({fields}) values{field_count}",
                table = Self::TABLE,
                fields = fields,
                field_count = Self::insert_field_counter(0),
            );
            for i in 1..items.len() {
                query_string.push(',');
                query_string.push_str(&Self::insert_field_counter(i));
            }
            if returning {
                query_string.push_str(RETURNING);
            }
            query_string.push(';');
            let mut q = sqlx::query(&query_string);

            for item in items {
                item.activate_fields();
                q = item.bind_to_query_insert(q);
            }
            match ret {
                ReturningEither::RowsAffected(ref mut n) => {
                    *n += q.execute(&mut *pool).await?.rows_affected();
                }
                ReturningEither::Items(ref mut items) => {
                    let mut inserted = q
                        .try_map(|x| Self::from_row(&x))
                        .fetch_all(&mut *pool)
                        .await?;
                    items.append(&mut inserted);
                }
            }
        }
        Ok(ret)
    }

    /// Updates a vec of items into the table.
    ///
    /// The approach of using a borrowed slice instead of an iterator is used,
    /// because it allows a little bit more flexibility for the caller.
    /// It is assumed that the performance cost of the DB call eclipses the cost
    /// of holding the slice.
    ///
    /// The argument `update_fields` contains the fields to be updated.
    /// If `selected_fields` is none, then all fields will be updated.
    ///
    /// NB: An update always uses the primary key for finding the match.
    /// TODO: Properly handle updates without PKey.
    async fn update_vec(
        items: &[Self],
        update_fields: Option<&[&str]>,
        pool: &mut sqlx::Transaction<Postgres>,
    ) -> Result<u64> {
        match Self::update_vec_inner(items, update_fields, None, pool).await? {
            ReturningEither::RowsAffected(x) => Ok(x),
            ReturningEither::Items(_) => panic!("`update_vec` returns rows."),
        }
    }

    /// This works as `update_vec`, however, it additionally takes a list of fields
    /// to return. And returns updated objects.
    ///
    /// NB: If the item does NOT have the `#[sqlx(default)]` attribute then
    /// `return_fields` must always be set to `None`.
    async fn update_vec_returning<D: std::fmt::Display + Send + Sync>(
        items: &[Self],
        update_fields: Option<&[&str]>,
        return_fields: Option<&[D]>,
        pool: &mut sqlx::Transaction<Postgres>,
    ) -> Result<Vec<Self>> {
        // Since the types D and &str are not "the same"...
        let return_fields = return_fields
            .map(|x| x.iter().map(|x| x.to_string()).collect::<Vec<_>>());
        let ret_fields = match return_fields {
            Some(ref f) => f.iter().map(|x| x as &str).collect::<Vec<_>>(),
            None => Self::FIELDS.to_vec(),
        };

        let r =
            Self::update_vec_inner(items, update_fields, Some(&ret_fields), pool);

        match r.await? {
            ReturningEither::Items(x) => Ok(x),
            ReturningEither::RowsAffected(_) => {
                panic!("`update_vec_returning` returns items.")
            }
        }
    }

    /// Presence of return fields decides whether we return fields or not.
    async fn update_vec_inner(
        items: &[Self],
        update_fields: Option<&[&str]>,
        return_fields: Option<&[&str]>,
        pool: &mut sqlx::Transaction<Postgres>,
    ) -> Result<ReturningEither<Self>> {
        use ReturningEither::*;
        let mut ret = ReturningEither::<Self>::new(return_fields.is_some());
        if items.is_empty() {
            return Ok(ret);
        }

        let t = 't';
        let upd = "upd";
        let update_fields = update_fields.map(Self::apply_tolerance_to_fields);
        let return_fields = return_fields.map(Self::apply_tolerance_to_fields);

        // It is preferable to only update selected fields, but all data in these fields
        // must be valid.
        let bind_mask = update_fields
            .as_ref()
            .map(|x| make_bind_mask::<Self>(x))
            .unwrap_or_else(|| make_bind_mask::<Self>(Self::UPDATE_FIELDS));

        // Define selected fields. We use the bind mask because it has some inbuilt
        // guarantees.

        // fields that should be set by this update (fields to update sans always autogen fields)
        let fields_to_set = update_set_fields_helper::<Self>(&bind_mask);
        // fields selected from the value list (keys + values to set to)
        let fields_to_select = select_fields_helper::<Self>(&bind_mask);

        // NB: This is very definitely optional.
        let return_clause = return_fields
            .map(|x| {
                let bind_mask = make_bind_mask::<Self>(&x);
                let fields = select_fields_helper::<Self>(&bind_mask)
                    .into_iter()
                    .map(|x| format!("{t}.{x}", t = t, x = x))
                    .collect::<Vec<_>>();
                format!(" RETURNING {}", fields.join(","))
            })
            .unwrap_or_default();

        for items in items.chunks(MAX_BINDINGS / fields_to_select.len()) {
            // Gives us `($1,$2,$3..)`
            let mut field_counts = field_counter(&fields_to_select, 0);
            for i in 1..items.len() {
                // The next two lines should together add `,($4,$5,$6..)`
                // The numbers increment by the number of fields each time.
                field_counts.push(',');
                field_counts.push_str(&field_counter(&fields_to_select, i));
            }

            // The final result of the next block should look like:
            // `field_a=upd.field_a,field_b=upd_field_b,field_c=upd.field_c`
            let field_mapping = fields_to_set
                .iter()
                .map(|x| format!("{f}={upd}.{f}", upd = upd, f = x))
                .collect::<Vec<_>>()
                .join(",");
            let where_clause = Self::PRIMARY_KEYS
                .iter()
                .map(|k| format!("{t}.{k}={upd}.{k}", t = t, upd = upd, k = k))
                .collect::<Vec<_>>()
                .join(" AND ");

            let query_string = format!(
                r#"UPDATE {table} AS {t} SET
                {field_mappings}
               FROM
                (values{field_counts}) AS {upd}({fields})
               WHERE {where_clause}{returning};"#,
                table = Self::TABLE,
                fields = fields_to_select.join(","),
                field_counts = field_counts,
                field_mappings = field_mapping,
                t = t,
                upd = upd,
                where_clause = where_clause,
                returning = return_clause,
            );
            let mut query = sqlx::query(&query_string);

            for item in items {
                query = item.bind_limited_fields(query, &bind_mask);
            }
            match ret {
                RowsAffected(ref mut n) => {
                    *n += query.execute(&mut *pool).await?.rows_affected();
                }
                Items(ref mut it) => {
                    let mut r = query
                        .try_map(|r| Self::from_row(&r))
                        .fetch_all(&mut *pool)
                        .await?;
                    it.append(&mut r);
                }
            }
        }
        Ok(ret)
    }

    /// This selects items from the table based on criteria and using the `Select` structure. Simple filtration
    /// operations as well as ordering and selection of specific fields is also possible.
    /// Trying to specify fields in the wrong order may cause an error to be returned, since the return structure
    /// is not flexible in the order of fields.
    async fn select<'a, Ex>(q: &Select, pool: Ex) -> Result<Vec<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        selection::SelectMaker::<Self>::start(q)
            .await?
            .stack()
            .await?
            .bind_and_execute(pool)
            .await
    }

    /// This selects a single item from the table based on criteria and using the `Select` structure. Simple filtration
    /// operations as well as ordering and selection of specific fields is also possible.
    /// Trying to specify fields in the wrong order may cause an error to be returned, since the return structure
    /// is not flexible in the order of fields.
    async fn select_single<'a, Ex>(q: &Select, pool: Ex) -> Result<Self>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        let mut items = selection::SelectMaker::<Self>::start(q)
            .await?
            .stack()
            .await?
            .bind_and_execute(pool)
            .await?;
        if let Some(item) = items.pop() {
            if !items.is_empty() {
                Err(SharedDbError::Other("select_single: too many items".into()))
            } else {
                Ok(item)
            }
        } else {
            Err(SharedDbError::Other("select_single: nothing is selected".into()))
        }
    }

    /// This selects possibly a single item from the table based on criteria and using the `Select` structure. Simple filtration
    /// operations as well as ordering and selection of specific fields is also possible.
    /// Trying to specify fields in the wrong order may cause an error to be returned, since the return structure
    /// is not flexible in the order of fields.
    async fn select_option<'a, Ex>(q: &Select, pool: Ex) -> Result<Option<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        let mut items = selection::SelectMaker::<Self>::start(q)
            .await?
            .stack()
            .await?
            .bind_and_execute(pool)
            .await?;
        let item = items.pop();
        if !items.is_empty() {
            Err(SharedDbError::Other("select_option: too many items".into()))
        } else {
            Ok(item)
        }
    }

    /// This function exists mostly for tests where we want to painlessly extract all records from a table
    async fn select_all<'a, Ex>(pool: Ex) -> Result<Vec<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        let q = Select::full::<Self>();
        selection::SelectMaker::<Self>::start(&q)
            .await?
            .stack()
            .await?
            .bind_and_execute(pool)
            .await
    }

    /// This function performs recursive select for the current table.
    ///
    /// The `initial_select` is used to select initial values.
    ///
    /// On each recursion step new rows are selected using their field named `new_item_field`
    /// that should have the same values as values of the field named `existing_item_field` of previously found rows.
    ///
    /// When no more rows are found, the resulting rows are processed using `final_select` query.
    ///
    /// Note that this select detects cycles in data, but do not report them.
    async fn select_recursive<'a, Ex>(
        initial_select: &Select,
        existing_item_field: &str,
        new_item_field: &str,
        final_select: &Select,
        pool: Ex,
    ) -> Result<Vec<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        // TODO use all fields for initial
        let mut initial_select = initial_select.clone();
        initial_select.field_list =
            Self::FIELDS.iter().copied().map(String::from).collect();
        let initial_maker = selection::SelectMaker::<Self>::start(&initial_select)
            .await?
            .stack()
            .await?;
        let rec_table = format!("rec_{}", Self::TABLE);
        let final_maker = selection::SelectMaker::<Self>::start_from(
            final_select,
            initial_maker.bind_count(),
            &rec_table,
            false,
        )
        .await?
        .stack()
        .await?;

        let fields =
            Self::FIELDS.iter().map(|f| format!("{}.{f}", Self::TABLE)).join(",");
        let pkeys = Self::PRIMARY_KEYS.iter().join(",");

        let query_string = format!(
            "
WITH RECURSIVE {rec_table} AS (
        {initial_select}
    UNION ALL
        SELECT {fields}
        FROM {rec_table}, {table}
        WHERE {table}.{new_item_field} = {rec_table}.{existing_item_field}
) CYCLE {pkeys} SET is_cycle USING path
{final_select};",
            initial_select = initial_maker.query_string(),
            table = Self::TABLE,
            final_select = final_maker.query_string()
        );

        let query = sqlx::query(&query_string);
        let query = initial_maker.bind_to_query(query);
        let query = final_maker.bind_to_query(query);
        query
            .try_map(|x| Self::from_row(&x))
            .fetch_all(pool)
            .await
            .map_err(Into::into)
    }

    async fn select_paginated<'a, Ex>(
        select: &Select,
        pool: Ex,
    ) -> Result<Paginated<Self>>
    where
        Ex: Executor<'a, Database = Postgres>,
    {
        let Select { offset: Some(offset), take_n: Some(take_n), count_total: Some(count_total), .. } = select else {
            return Err(SharedDbError::Other("select is not suitable for paged query".to_string()));
        };
        let (items, total) = if *count_total {
            let items_with_count: Vec<_> =
                selection::SelectMaker::<Self>::start_with_count(select)
                    .await?
                    .stack()
                    .await?
                    .bind()
                    .try_map(|x| WithCount::<Self>::from_row(&x))
                    .fetch_all(pool)
                    .await?;
            let total_count = match items_with_count.get(0) {
                None if *offset == 0 => Some(0),
                Some(item_with_count) => Some(item_with_count.total_count()),
                _ => {
                    tracing::warn!(
                        "empty chunk at offset={offset} and take_n={take_n}"
                    );
                    None
                }
            };
            let items =
                items_with_count.into_iter().map(WithCount::into_item).collect();
            (items, total_count)
        } else {
            let items = selection::SelectMaker::<Self>::start(select)
                .await?
                .stack()
                .await?
                .bind_and_execute(pool)
                .await?;
            (items, None)
        };
        Ok(Paginated { items, total })
    }
}

/// Marker trait for DbItem structs that can be built from
/// subset of fields.
///
/// Implementation is generated along with derived `DbItem` if no `item_field_required` attribute is applied.
pub trait DbItemPartialSelect {}
