use std::marker::PhantomData;

use ahash::AHashSet;

use crate::{DbAdaptor, DbItem};

/// Field mask used for DB operations.
#[derive(Debug, Clone)]
pub struct DbFieldMask<T> {
    fields: Vec<bool>,
    _phantom_data: PhantomData<T>,
}

impl<T> DbFieldMask<T>
where
    T: DbItem,
{
    /// Use all fields.
    pub fn all() -> Self {
        DbFieldMask {
            fields: vec![true; T::FIELDS.len()],
            _phantom_data: Default::default(),
        }
    }

    /// Use no fields.
    pub fn none() -> Self {
        DbFieldMask {
            fields: vec![false; T::FIELDS.len()],
            _phantom_data: Default::default(),
        }
    }

    /// Use only fields with specified names.
    pub fn with_fields<'a, I, S>(fields: I) -> Self
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        let mut mask = DbFieldMask::none();
        mask.set_by_name(true, fields);
        mask
    }

    pub fn with_pkeys(mut self) -> Self {
        self.set_pkeys();
        self
    }

    pub fn without_autogen(mut self) -> Self {
        self.unset_always_autogen();
        self
    }

    /// Field mask used for `bind` operation in Sqlx.
    ///
    /// Always includes key fields.
    pub fn make_bind_mask<'a, I, S>(fields: I) -> Self
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        Self::with_fields(fields).with_pkeys()
    }

    /// Field mask used for update operations.
    ///
    /// Always includes key fields and excludes auto generated fields.
    pub fn make_single_update_bind_mask<'a, I, S>(fields: I) -> Self
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        Self::with_fields(fields).with_pkeys().without_autogen()
    }

    /// Collects selected field names.
    pub fn to_fields<I: FromIterator<&'static str>>(&self) -> I {
        std::iter::zip(T::FIELDS, &self.fields)
            .filter_map(|(f, m)| m.then_some(*f))
            .collect()
    }

    /// Constructs negated mask.
    pub fn inverted(&self) -> Self {
        Self {
            fields: self.fields.iter().map(|x| !*x).collect(),
            _phantom_data: Default::default(),
        }
    }

    /// Iterates over the mask as a sequence of boolean values.
    pub fn iter(&self) -> impl Iterator<Item = &bool> {
        self.fields.iter()
    }

    /// For each fields with names specified in `fields`, sets its presence to `value`;
    fn set_by_name<'a, I, S>(&mut self, value: bool, fields: I)
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        let fields = fields.into_iter().map(AsRef::as_ref).collect::<AHashSet<_>>();
        for (idx, field) in T::FIELDS.iter().enumerate() {
            if fields.contains(field) {
                self.fields[idx] = value;
            }
        }
    }

    /// For each fields with indices specified by `indices`, sets its presence to `value`.
    ///
    /// NB. This function should only be used with values generated by proc
    /// macro for this `T` (`T::..._INDICES`), as it can result `panic` if
    /// `indices` contain values that are out of bounds.
    fn set(&mut self, value: bool, indices: &[usize]) {
        for i in indices {
            self.fields[*i] = value;
        }
    }

    /// Adds all key fields.
    fn set_pkeys(&mut self) {
        self.set(true, T::PRIMARY_KEY_INDICES);
    }

    /// Removes all auto generated fields.
    fn unset_always_autogen(&mut self) {
        self.set(false, T::NO_UPDATE_INDICES);
    }
}

impl<T> std::ops::Index<usize> for DbFieldMask<T> {
    type Output = bool;

    fn index(&self, index: usize) -> &Self::Output {
        &self.fields[index]
    }
}

impl<T> std::ops::IndexMut<usize> for DbFieldMask<T> {
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.fields[index]
    }
}

impl<T> std::ops::BitOr for DbFieldMask<T> {
    type Output = DbFieldMask<T>;

    fn bitor(mut self, rhs: Self) -> Self::Output {
        std::iter::zip(&mut self.fields, rhs.fields)
            .for_each(|(l, r)| *l = *l || r);
        self
    }
}

impl<T> PartialEq for DbFieldMask<T> {
    fn eq(&self, other: &Self) -> bool {
        self.fields == other.fields
    }
}

impl<T, const N: usize> PartialEq<[bool; N]> for DbFieldMask<T> {
    fn eq(&self, other: &[bool; N]) -> bool {
        self.fields.as_slice() == &other[..]
    }
}

impl<T> PartialEq<[bool]> for DbFieldMask<T> {
    fn eq(&self, other: &[bool]) -> bool {
        self.fields.as_slice() == other
    }
}

pub struct DbAdaptorFieldMask<T: DbAdaptor> {
    item_field_mask: DbFieldMask<T::DbItem>,
    dup_field_mask: Vec<bool>,
}

impl<T: DbAdaptor> DbAdaptorFieldMask<T> {
    pub fn all() -> Self {
        DbAdaptorFieldMask {
            item_field_mask: DbFieldMask::all(),
            dup_field_mask: vec![true; T::DUP_FIELDS.len()],
        }
    }

    pub fn none() -> Self {
        DbAdaptorFieldMask {
            item_field_mask: DbFieldMask::none(),
            dup_field_mask: vec![false; T::DUP_FIELDS.len()],
        }
    }

    /// Use only fields with specified names.
    pub fn with_fields<'a, I, S>(fields: I) -> Self
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        // Сразу собираем AHashSet, такой же, как используется под капотом `DbFieldMask::with_fields`,
        // т.к. он понадобится для дублей, а потом и для основных полей, где (при включенной опримизации)
        // будет использован напрямую, без копирования.
        let fields = fields.into_iter().map(AsRef::as_ref).collect::<AHashSet<_>>();
        let dup_field_mask =
            T::DUP_FIELDS.iter().map(|f| fields.contains(f)).collect();
        let item_field_mask = DbFieldMask::with_fields(&fields);
        DbAdaptorFieldMask {
            item_field_mask,
            dup_field_mask,
        }
    }

    /// Use only fields with specified names.
    pub fn with_fields_and_pkeys<'a, I, S>(fields: I) -> Self
    where
        I: IntoIterator<Item = &'a S>,
        S: 'a + AsRef<str>,
    {
        // Сразу собираем AHashSet, такой же, как используется под капотом `DbFieldMask::with_fields`,
        // т.к. он понадобится для дублей, а потом и для основных полей, где (при включенной опримизации)
        // будет использован напрямую, без копирования.
        let fields = fields.into_iter().map(AsRef::as_ref).collect::<AHashSet<_>>();
        let dup_field_mask =
            T::DUP_FIELDS.iter().map(|f| fields.contains(f)).collect();
        let item_field_mask = DbFieldMask::with_fields(&fields).with_pkeys();
        DbAdaptorFieldMask {
            item_field_mask,
            dup_field_mask,
        }
    }

    pub fn item_field_mask(&self) -> &DbFieldMask<T::DbItem> {
        &self.item_field_mask
    }

    pub fn dup_field_mask(&self) -> &[bool] {
        &self.dup_field_mask
    }
}
