use crate::legacy::plans::PlanStatus;
use crate::PlanRetrospective;
use asez2_shared_db::test_setup::run_db_test;
use asez2_shared_db::DbItem;
use sqlx::FromRow;

const CREATE_TABLE: &str = "(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_uuid uuid NOT NULL,
    plan_id BIGINT NOT NULL,
    plan_year SMALLINT NOT NULL,
    id_ly BIGINT,
    uuid_ly uuid,
    is_removed BOOLEAN,
    plan_status SMALLINT NOT NULL -- Maybe just status.
    )";

#[tokio::test]
async fn plan_retrospective_table() {
    run_db_test(
        PlanRetrospective::TABLE,
        CREATE_TABLE,
        None,
        |mut pool| async move {
            let mut new = PlanRetrospective {
                id: 1,
                plan_uuid: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11".parse().unwrap(),
                plan_id: 0,
                plan_year: 2024,
                plan_status: PlanStatus::AnalysisCompletedD646,
                id_ly: 0,
                uuid_ly: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11".parse().unwrap(),
                is_removed: false,
            };

            let for_update = PlanRetrospective {
                id: 1,
                plan_uuid: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11".parse().unwrap(),
                plan_id: 0,
                plan_year: 2024,
                plan_status: PlanStatus::AnalysisPerformedD646,
                id_ly: 0,
                uuid_ly: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11".parse().unwrap(),
                is_removed: false,
            };

            let r = new.insert(&mut pool).await.unwrap();

            assert_eq!(r, 1);

            let days = sqlx::query(" select * from plan_retrospective;")
                .map(|x| PlanRetrospective::from_row(&x).unwrap())
                .fetch_all(&mut pool)
                .await
                .unwrap();

            assert_eq!(days[0], new);

            let x = for_update.update(None, &mut pool).await.unwrap();

            assert_eq!(x, 1);

            let days = sqlx::query(" select * from plan_retrospective;")
                .map(|x| PlanRetrospective::from_row(&x).unwrap())
                .fetch_all(&mut pool)
                .await
                .unwrap();

            assert_eq!(days[0], for_update);
        },
    )
    .await
}
