

-- This table is INCOMPLETE.
CREATE TABLE public.contract_amendment_item_legacy(
    uuid uuid NOT NULL PRIMARY KEY, 
    header_uuid uuid NOT NULL,
    number SMALLINT NOT NULL, 
    source_uuid uuid NOT NULL, 
    description_internal character varying NOT NULL,
    description_external character varying NOT NULL,
    product_type_id SMALLINT NOT NULL, 
    category_id SMALLINT NOT NULL, 
    budget_item_id SMALLINT NOT NULL, 
    payment_balance_item_id SMALLINT NOT NULL, 
    consumer_id INTEGER NOT NULL,
    okpd2_id INTEGER NOT NULL,
    okved2_id SMALLINT NOT NULL, 
    okato_id INTEGER NOT NULL,
    is_not_russian_delivery BOOLEAN NOT NULL,
    delivery_basis character varying NOT NULL,
    unit_id SMALLINT NOT NULL, 
    quantity BIGINT NOT NULL, 
    price BIGINT NOT NULL, 
    price_unit INTEGER NOT NULL,
    currency_id SMALLINT NOT NULL, 
    currency_rate BIGINT NOT NULL, 
    currency_rate_date date NOT NULL, 
    vat_id SMALLINT NOT NULL, 
    transportation_price BIGINT NOT NULL, 
    transportation_vat_id SMALLINT NOT NULL, 
    transportation_sum_included_vat BIGINT NOT NULL, 
    sum_excluded_vat BIGINT NOT NULL, 
    sum_vat BIGINT NOT NULL, 
    sum_included_vat BIGINT NOT NULL, 
    sum_excluded_vat_rub BIGINT NOT NULL, 
    sum_vat_rub BIGINT NOT NULL, 
    sum_included_vat_rub BIGINT NOT NULL, 
    delivery_start_date date NOT NULL, 
    delivery_end_date date NOT NULL, 
    price_source_1_text character varying NOT NULL,
    price_source_1_price BIGINT NOT NULL, 
    price_source_1_date date NOT NULL, 
    price_source_2_text character varying NOT NULL,
    price_source_2_price BIGINT NOT NULL, 
    price_source_2_date date NOT NULL, 
    price_source_3_text character varying NOT NULL,
    price_source_3_price BIGINT NOT NULL, 
    price_source_3_date date NOT NULL, 
    is_analog_allowed BOOLEAN NOT NULL,
    analog_price BIGINT NOT NULL, 
    analog_text character varying NOT NULL,
    analog_producer_id INTEGER NOT NULL,
    analog_producer_text character varying NOT NULL,
    analog_country_id SMALLINT NOT NULL, 
    analog_requirements character varying NOT NULL,
    mark character varying NOT NULL,
    mark_main character varying NOT NULL,
    technical_characteristics character varying NOT NULL,
    technical_requirements character varying NOT NULL,
    gosts character varying NOT NULL,
    material_code_local character varying NOT NULL,
    material_code_ius_mtr character varying NOT NULL,
    is_serial BOOLEAN NOT NULL,
    pzp_code character varying NOT NULL,
    nomenclature_group_id SMALLINT NOT NULL, 
    source_country_id SMALLINT NOT NULL, 
    producer_country_id SMALLINT NOT NULL, 
    producer_id INTEGER NOT NULL,
    previous_price BIGINT NOT NULL, 
    previous_delivery_date date NOT NULL, 
    investment_project_id INTEGER NOT NULL,
    is_dealer BOOLEAN NOT NULL,
    is_material_registry BOOLEAN NOT NULL,
    certificate_holder_id INTEGER NOT NULL,
    certificate_text character varying NOT NULL,
    certificate_number character varying NOT NULL,
    is_centralized_delivery BOOLEAN NOT NULL,
    centralized_sum BIGINT NOT NULL, 
    prepayment_percent BIGINT NOT NULL, 
    payment_delay SMALLINT NOT NULL, 
    psd_price BIGINT NOT NULL, 
    psd_date date NOT NULL, 
    psd_code character varying NOT NULL,
    onm_price BIGINT NOT NULL, 
    material_registry_price BIGINT NOT NULL, 
    expert_price BIGINT NOT NULL, 
    expert_sum_included_vat BIGINT NOT NULL, 
    pricing_quantity BIGINT NOT NULL, 
    pricing_unit_id SMALLINT NOT NULL, 
    pricing_price BIGINT NOT NULL, 
    pricing_vat_id SMALLINT NOT NULL, 
    pricing_currency_id SMALLINT NOT NULL, 
    pricing_currency_rate BIGINT NOT NULL, 
    pricing_transportation_price BIGINT NOT NULL, 
    pricing_transportation_vat_id SMALLINT NOT NULL, 
    pricing_department_id INTEGER NOT NULL,
    pricing_expert_id INTEGER NOT NULL,
    pricing_method_id SMALLINT NOT NULL, 
    pricing_resume character varying NOT NULL,
    status_id SMALLINT NOT NULL, 
    is_removed BOOLEAN NOT NULL,
    created_at timestamp without time zone NOT NULL,
    changed_at timestamp without time zone NOT NULL,
    created_by INTEGER NOT NULL,
    changed_by INTEGER NOT NULL
)
TABLESPACE pg_default;

COMMENT ON TABLE public.contract_amendment_item_legacy
    IS 'Таблица статей ДС';

COMMENT ON COLUMN public.contract_amendment_item_legacy.uuid
    IS 'Уникальный идентификатор записи';
