

-- This table is INCOMPLETE. It is also not clear whether it is valid or not.
CREATE TABLE public.contract_amendment_legacy(
    uuid uuid NOT NULL PRIMARY KEY,
    id character varying NOT NULL,
    header_uuid uuid NOT NULL,
    header_id character varying NOT NULL,
    is_actual BOOLEAN NOT NULL,
    is_closed BOOLEAN NOT NULL,
    version_type SMALLINT NOT NULL,
    version_number SMALLINT NOT NULL,
    active_uuid uuid NOT NULL,
    source_uuid uuid NOT NULL,
    posting_date date NOT NULL,
    year SMALLINT NOT NULL,
    customer_id INTEGER NOT NULL,
    declarant_id INTEGER NOT NULL,
    agent_id INTEGER NOT NULL,
    initiator_user_id INTEGER NOT NULL,
    tender_user_id INTEGER NOT NULL,
    organizer_id INTEGER NOT NULL,
    section_id SMALLINT NOT NULL,
    contract_subject character varying NOT NULL,
    minimal_requirements character varying NOT NULL,
    customer_note character varying NOT NULL,
    number_customer character varying NOT NULL,
    number_cgg character varying NOT NULL,
    currency_id SMALLINT NOT NULL,
    currency_rate BIGINT NOT NULL,
    vat_id SMALLINT NOT NULL,
    sum_excluded_vat BIGINT NOT NULL,
    sum_vat BIGINT NOT NULL,
    sum_included_vat BIGINT NOT NULL,
    sum_excluded_vat_rub BIGINT NOT NULL,
    sum_vat_rub BIGINT NOT NULL,
    sum_included_vat_rub BIGINT NOT NULL,
    purchasing_method_id SMALLINT NOT NULL,
    purchasing_type_id SMALLINT NOT NULL,
    purchasing_kind_id SMALLINT NOT NULL,
    regulation_document_id SMALLINT NOT NULL,
    publication_type_id SMALLINT NOT NULL,
    master_system_id SMALLINT NOT NULL,
    funding_source_id SMALLINT NOT NULL,
    purchasing_trend_id SMALLINT NOT NULL,
    budget_item_id SMALLINT NOT NULL,
    payment_balance_item_id SMALLINT NOT NULL,
    is_smb BOOLEAN NOT NULL,
    is_smb_sub BOOLEAN NOT NULL,
    smb_exception_id SMALLINT NOT NULL,
    smb_sub_percent SMALLINT NOT NULL,
    smb_sub_sum BIGINT NOT NULL,
    documentation_date date NOT NULL,
    publication_date date NOT NULL,
    summing_up_date date NOT NULL,
    contract_sign_date date NOT NULL,
    delivery_start_date date NOT NULL,
    delivery_end_date date NOT NULL,
    supplier_id INTEGER NOT NULL,
    supplier_text character varying NOT NULL,
    single_supplier_reason_id SMALLINT NOT NULL,
    single_supplier_expert_id INTEGER NOT NULL,
    single_supplier_decision_id SMALLINT NOT NULL,
    single_supplier_decision_resume character varying NOT NULL,
    is_affiliated BOOLEAN NOT NULL,
    is_supplier_smb BOOLEAN NOT NULL,
    is_commission BOOLEAN NOT NULL,
    is_competitive_now BOOLEAN NOT NULL,
    management_order_number character varying NOT NULL,
    management_order_date date NOT NULL,
    reason_document character varying NOT NULL,
    is_approved_by_d646 BOOLEAN NOT NULL,
    is_price_analysis_by_d646 BOOLEAN NOT NULL,
    is_approved_by_d647 BOOLEAN NOT NULL,
    is_onm BOOLEAN NOT NULL,
    is_agent_fee BOOLEAN NOT NULL,
    agent_contract_number character varying NOT NULL,
    is_design_stage BOOLEAN NOT NULL,
    repair_stage_id SMALLINT NOT NULL,
    is_gas_supply BOOLEAN NOT NULL,
    is_little_cost BOOLEAN NOT NULL,
    is_banking_support BOOLEAN NOT NULL,
    is_innovative BOOLEAN NOT NULL,
    is_to_publish BOOLEAN NOT NULL,
    rationale_for_not_publication character varying NOT NULL,
    rationale_for_publication character varying NOT NULL,
    is_cooperative BOOLEAN NOT NULL,
    is_not_purchase BOOLEAN NOT NULL,
    is_under_control BOOLEAN NOT NULL,
    rationale_is_under_control character varying NOT NULL,
    technical_developer character varying NOT NULL,
    limit_on_construction BIGINT NOT NULL,
    limit_on_works BIGINT NOT NULL,
    priority SMALLINT NOT NULL,
    is_priority_project BOOLEAN NOT NULL,
    priority_project_document character varying NOT NULL,
    is_priority_introductory BOOLEAN NOT NULL,
    priority_introductory_date date NOT NULL,
    priority_introductory_document character varying NOT NULL,
    is_priority_repair BOOLEAN NOT NULL,
    priority_repair_document character varying NOT NULL,
    is_priority_ozp BOOLEAN NOT NULL,
    priority_ozp_document character varying NOT NULL,
    is_priority_income_contract BOOLEAN NOT NULL,
    priority_income_contract_document character varying NOT NULL,
    priority_income_contract_partner_id INTEGER NOT NULL,
    priority_income_contract_partner_text character varying NOT NULL,
    is_priority_other BOOLEAN NOT NULL,
    is_headquarters BOOLEAN NOT NULL,
    is_first_time BOOLEAN NOT NULL,
    is_list_price BOOLEAN NOT NULL,
    pricing_method_id SMALLINT NOT NULL,
    is_no_qualification BOOLEAN NOT NULL,
    qualification_id INTEGER NOT NULL,
    extract_number_d646 character varying NOT NULL,
    extract_date_d646 date NOT NULL,
    extract_sum_included_vat_rub_d646 BIGINT NOT NULL,
    extract_number_d647 character varying NOT NULL,
    extract_date_d647 date NOT NULL,
    extract_sum_included_vat_rub_d647 BIGINT NOT NULL,
    product_type_id SMALLINT NOT NULL,
    organizer_note character varying NOT NULL,
    description character varying NOT NULL,
    status_scheme_id SMALLINT NOT NULL,
    status_id SMALLINT NOT NULL,
    is_removed BOOLEAN NOT NULL,
    created_at timestamp without time zone NOT NULL,
    changed_at timestamp without time zone NOT NULL,
    created_by INTEGER NOT NULL,
    changed_by INTEGER NOT NULL
)
TABLESPACE pg_default;

COMMENT ON TABLE public.contract_amendment_legacy
    IS 'Таблица заголовок ДС';

COMMENT ON COLUMN public.contract_amendment_legacy.uuid
    IS 'Уникальный идентификатор записи';
