

CREATE TABLE public.contract_amendment_item (
    header_uuid uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    uuid uuid NOT NULL,
    id bigint NOT NULL,
    number smallint DEFAULT 0 NOT NULL,
    active_uuid uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    source_uuid uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    description_internal character varying(1000) DEFAULT ''::character varying NOT NULL,
    description_external character varying(1000) DEFAULT ''::character varying NOT NULL,
    product_type_id smallint DEFAULT 0 NOT NULL,
    kind_id smallint DEFAULT 0 NOT NULL,
    category_id smallint DEFAULT 0 NOT NULL,
    budget_item_id smallint DEFAULT 0 NOT NULL,
    payment_balance_item_id smallint DEFAULT 0 NOT NULL,
    investment_project_id integer DEFAULT 0 NOT NULL,
    okpd2_id integer DEFAULT 0 NOT NULL,
    okved2_id smallint DEFAULT 0 NOT NULL,
    okato_id integer DEFAULT 0 NOT NULL,
    is_not_russian_delivery boolean DEFAULT false NOT NULL,
    delivery_basis character varying(1000) DEFAULT ''::character varying NOT NULL,
    consumer_id integer DEFAULT 0 NOT NULL,
    quantity bigint DEFAULT 0 NOT NULL,
    unit_id smallint DEFAULT 0 NOT NULL,
    price bigint DEFAULT 0 NOT NULL,
    price_unit smallint DEFAULT 0 NOT NULL,
    vat_id smallint DEFAULT 0 NOT NULL,
    sum_excluded_vat bigint DEFAULT 0 NOT NULL,
    sum_vat bigint DEFAULT 0 NOT NULL,
    sum_included_vat bigint DEFAULT 0 NOT NULL,
    currency_id smallint DEFAULT 0 NOT NULL,
    currency_rate bigint DEFAULT 0 NOT NULL,
    currency_rate_date date DEFAULT '1900-01-01'::date NOT NULL,
    sum_excluded_vat_rub bigint DEFAULT 0 NOT NULL,
    sum_vat_rub bigint DEFAULT 0 NOT NULL,
    sum_included_vat_rub bigint DEFAULT 0 NOT NULL,
    delivery_start_date date DEFAULT '1900-01-01'::date NOT NULL,
    delivery_end_date date DEFAULT '1900-01-01'::date NOT NULL,
    initial_quantity bigint DEFAULT 0 NOT NULL,
    initial_unit_id smallint DEFAULT 0 NOT NULL,
    initial_price bigint DEFAULT 0 NOT NULL,
    initial_price_unit integer DEFAULT 0 NOT NULL,
    initial_vat_id smallint DEFAULT 0 NOT NULL,
    initial_sum_excluded_vat bigint DEFAULT 0 NOT NULL,
    initial_sum_vat bigint DEFAULT 0 NOT NULL,
    initial_sum_included_vat bigint DEFAULT 0 NOT NULL,
    initial_currency_id smallint DEFAULT 0 NOT NULL,
    initial_currency_rate bigint DEFAULT 0 NOT NULL,
    initial_currency_rate_date date DEFAULT '1900-01-01'::date NOT NULL,
    initial_sum_excluded_vat_rub bigint DEFAULT 0 NOT NULL,
    initial_sum_vat_rub bigint DEFAULT 0 NOT NULL,
    initial_sum_included_vat_rub bigint DEFAULT 0 NOT NULL,
    initial_delivery_start_date date DEFAULT '1900-01-01'::date NOT NULL,
    initial_delivery_end_date date DEFAULT '1900-01-01'::date NOT NULL,
    previous_quantity bigint DEFAULT 0 NOT NULL,
    previous_unit_id smallint DEFAULT 0 NOT NULL,
    previous_price bigint DEFAULT 0 NOT NULL,
    previous_price_unit integer DEFAULT 0 NOT NULL,
    previous_vat_id smallint DEFAULT 0 NOT NULL,
    previous_sum_excluded_vat bigint DEFAULT 0 NOT NULL,
    previous_sum_vat bigint DEFAULT 0 NOT NULL,
    previous_sum_included_vat bigint DEFAULT 0 NOT NULL,
    previous_currency_id smallint DEFAULT 0 NOT NULL,
    previous_currency_rate bigint DEFAULT 0 NOT NULL,
    previous_currency_rate_date date DEFAULT '1900-01-01'::date NOT NULL,
    previous_sum_excluded_vat_rub bigint DEFAULT 0 NOT NULL,
    previous_sum_vat_rub bigint DEFAULT 0 NOT NULL,
    previous_sum_included_vat_rub bigint DEFAULT 0 NOT NULL,
    previous_delivery_start_date date DEFAULT '1900-01-01'::date NOT NULL,
    previous_delivery_end_date date DEFAULT '1900-01-01'::date NOT NULL,
    material_code_local character varying(40) DEFAULT ''::character varying NOT NULL,
    material_code_ius_mtr character varying(18) DEFAULT ''::character varying NOT NULL,
    is_serial boolean DEFAULT false NOT NULL,
    pzp_code character varying(40) DEFAULT ''::character varying NOT NULL,
    nomenclature_group_id smallint DEFAULT 0 NOT NULL,
    source_country_id smallint DEFAULT 0 NOT NULL,
    producer_country_id smallint DEFAULT 0 NOT NULL,
    producer_id integer DEFAULT 0 NOT NULL,
    is_dealer boolean DEFAULT false NOT NULL,
    repair_summary_code character varying(60) DEFAULT ''::character varying NOT NULL,
    repair_inventory_number character varying(100) DEFAULT ''::character varying NOT NULL,
    repair_text character varying(1000) DEFAULT ''::character varying NOT NULL,
    repair_plan_code character varying(100) DEFAULT ''::character varying NOT NULL,
    is_material_registry boolean DEFAULT false NOT NULL,
    certificate_holder_id integer DEFAULT 0 NOT NULL,
    certificate_holder_text character varying(200) DEFAULT ''::character varying NOT NULL,
    certificate_text character varying(1000) DEFAULT ''::character varying NOT NULL,
    certificate_number character varying(25) DEFAULT ''::character varying NOT NULL,
    is_removed boolean DEFAULT false NOT NULL,
    delta_quantity bigint,
    delta_price bigint,
    delta_price_rub bigint,
    delta_sum_vat bigint,
    delta_sum_vat_rub bigint,
    delta_sum_excluded_vat bigint,
    delta_sum_excluded_vat_rub bigint,
    delta_sum_included_vat bigint,
    delta_sum_included_vat_rub bigint,
    uuid_item_proposal bigint,
    pricing_quantity bigint DEFAULT 0 NOT NULL,
    pricing_unit_id smallint NOT NULL,
    pricing_price bigint DEFAULT 0 NOT NULL,
    pricing_price_rub bigint,
    pricing_department_id integer DEFAULT 0 NOT NULL,
    pricing_expert_id integer DEFAULT 0 NOT NULL,
    pricing_method_id smallint DEFAULT 0 NOT NULL,
    pricing_resume character varying(1000) DEFAULT ''::character varying NOT NULL,
    pricing_vat_id smallint DEFAULT 0 NOT NULL,
    pricing_currency_id smallint NOT NULL,
    pricing_currency_rate bigint,
    pricing_currency_rate_date date,
    pricing_sum_excluded_vat bigint,
    pricing_sum_excluded_vat_rub bigint,
    pricing_sum_included_vat bigint,
    pricing_sum_included_vat_rub bigint,
    pricing_sum_vat bigint,
    pricing_sum_vat_rub bigint,
    pricing_transportation_vat_id smallint DEFAULT 0 NOT NULL,
    pricing_transportation_price bigint DEFAULT 0 NOT NULL,
    pricing_transportation_price_rub bigint DEFAULT 0,
    pricing_transportation_sum_vat bigint DEFAULT 0,
    pricing_transportation_sum_vat_rub bigint DEFAULT 0,
    pricing_transportation_sum_included_vat bigint DEFAULT 0,
    pricing_transportation_sum_included_vat_rub bigint DEFAULT 0,
    pricing_total_sum bigint,
    pricing_total_sum_rub bigint,
    pricing_delta_unit_id bigint,
    pricing_delta_quantity bigint,
    pricing_delta_currency_id bigint,
    pricing_delta_currency_rate bigint,
    pricing_delta_currency_rate_date date,
    pricing_delta_price bigint,
    pricing_delta_price_rub bigint,
    pricing_delta_sum_excluded_vat bigint,
    pricing_delta_sum_excluded_vat_rub bigint,
    pricing_delta_sum_vat bigint,
    pricing_delta_sum_vat_rub bigint,
    pricing_delta_sum_included_vat bigint,
    pricing_delta_sum_included_vat_rub bigint,
    pricing_delta_transportation_price bigint DEFAULT 0,
    pricing_delta_transportation_price_rub bigint DEFAULT 0,
    pricing_delta_transportation_sum_vat bigint DEFAULT 0,
    pricing_delta_transportation_sum_vat_rub bigint DEFAULT 0,
    pricing_delta_transportation_sum_included_vat bigint DEFAULT 0,
    pricing_delta_transportation_sum_included_vat_rub bigint DEFAULT 0,
    pricing_delta_total_sum bigint,
    pricing_delta_total_sum_rub bigint,
    created_at timestamp without time zone NOT NULL,
    changed_at timestamp without time zone NOT NULL,
    created_by integer NOT NULL,
    changed_by integer NOT NULL,
    pricing_created_at timestamp without time zone DEFAULT '2024-12-23 00:00:00'::timestamp without time zone NOT NULL,
    pricing_changed_at timestamp without time zone DEFAULT '2024-12-23 00:00:00'::timestamp without time zone NOT NULL
);

ALTER TABLE ONLY public.contract_amendment_item
    ADD CONSTRAINT contract_amendment_item_pkey PRIMARY KEY (uuid);

COMMENT ON COLUMN public.contract_amendment_item.uuid IS 'Уникальный идентификатор записи';



COMMENT ON COLUMN public.contract_amendment_item.id IS 'Внешний идентификатор записи (10 значное число)';



COMMENT ON COLUMN public.contract_amendment_item.created_at IS 'Дата создания';



COMMENT ON COLUMN public.contract_amendment_item.changed_at IS 'Дата изменения';



COMMENT ON COLUMN public.contract_amendment_item.created_by IS 'Идентификатор создателя';



COMMENT ON COLUMN public.contract_amendment_item.changed_by IS 'Идентификатор того, кто изменил';
