-- Имеет такие же поля как и plan + дополнительные для версионности


CREATE TABLE public.plan_version (
    uuid uuid NOT NULL,
    id bigint NOT NULL,
    version_type smallint DEFAULT 0 NOT NULL,
    version_number smallint DEFAULT 0 NOT NULL,
    posting_date date DEFAULT '1901-01-01'::date NOT NULL,
    year smallint DEFAULT (date_part('year'::text, now()))::smallint NOT NULL,
    commission_kind_id smallint NOT NULL,
    commission_date date,
    customer_id integer NOT NULL,
    supplier_id integer NOT NULL,
    supplier_text character varying(255),
    contract_subject text NOT NULL,
    sum_excluded_vat bigint NOT NULL,
    sum_excluded_vat_rub bigint NOT NULL,
    sum_vat bigint DEFAULT 0 NOT NULL,
    currency_id smallint NOT NULL,
    currency_rate bigint NOT NULL,
    for_price_analysis boolean DEFAULT false NOT NULL,
    executor_method_id smallint DEFAULT 0 NOT NULL,
    purchasing_type_id smallint NOT NULL,
    status_id smallint NOT NULL,
    section_id smallint DEFAULT 0 NOT NULL,
    delivery_start_date date NOT NULL,
    delivery_end_date date NOT NULL,
    kod_st_buda character varying(10),
    okdp2 character varying(20),
    category_id character varying(20),
    code_type smallint,
    declarant_id integer DEFAULT 0 NOT NULL,
    agent_id integer DEFAULT 0 NOT NULL,
    initiator_user_id integer DEFAULT 0 NOT NULL,
    tender_user_id integer DEFAULT 0 NOT NULL,
    organizer_id integer,
    minimal_requirements character varying(2000) DEFAULT ''::text NOT NULL,
    customer_note character varying(1000),
    number_customer character varying(40) DEFAULT ''::text NOT NULL,
    number_cgg character varying(64),
    vat_id smallint DEFAULT 0 NOT NULL,
    sum_included_vat bigint DEFAULT 0 NOT NULL,
    sum_included_vat_rub bigint DEFAULT 0 NOT NULL,
    purchasing_method_id smallint DEFAULT 0 NOT NULL,
    purchasing_kind_id smallint DEFAULT 0 NOT NULL,
    regulation_document_id integer DEFAULT 0 NOT NULL,
    publication_type_id smallint DEFAULT 0 NOT NULL,
    master_system_id smallint,
    funding_source_id smallint DEFAULT 0 NOT NULL,
    purchasing_trend_id smallint DEFAULT 0 NOT NULL,
    is_smb boolean,
    is_smb_sub boolean,
    smb_exception_id smallint,
    smb_sub_percent bigint,
    smb_sub_sum bigint,
    documentation_date date,
    publication_date date,
    summing_up_date date,
    contract_sing_date date,
    single_supplier_reason_id smallint DEFAULT 0 NOT NULL,
    single_supplier_expert_id integer,
    single_supplier_decision_id integer,
    single_supplier_decision_resume character varying(2000),
    is_affiliated boolean,
    is_supplier_smb boolean,
    is_competitive_now boolean,
    management_order_number integer,
    management_order_date date,
    reason_document character varying(63),
    is_approved_by_d646 boolean DEFAULT false NOT NULL,
    is_price_analysis_by_d646 boolean,
    is_approver_by_d647 boolean,
    is_onm boolean,
    is_agent_fee boolean,
    agent_contract_number character varying(60),
    is_design_stage boolean,
    repair_stage_id smallint,
    is_gas_supply boolean,
    is_little_cost boolean,
    is_banking_support boolean DEFAULT false NOT NULL,
    is_innovative boolean,
    is_to_publish boolean DEFAULT false NOT NULL,
    rationale_for_not_publication character varying(1000),
    rationale_for_publication character varying(1000),
    is_cooperative boolean,
    is_not_purchase boolean,
    is_under_control boolean,
    rationale_is_under_control character varying(1000),
    technical_developer character varying(100),
    is_priority_project boolean DEFAULT false NOT NULL,
    priority_project_document character varying(100),
    is_priority_introductory boolean DEFAULT false NOT NULL,
    priority_introductory_date date,
    priority_introductory_document character varying(100),
    is_priority_repair boolean DEFAULT false NOT NULL,
    priority_repair_document character varying(100),
    is_priority_ozp boolean DEFAULT false NOT NULL,
    priority_ozp_document character varying(100),
    is_priority_income_contract boolean DEFAULT false NOT NULL,
    priority_income_contract_document character varying(100),
    priority_income_contract_partner_id integer,
    is_priority_other boolean DEFAULT false NOT NULL,
    is_headquarters boolean DEFAULT false NOT NULL,
    is_first_time boolean,
    is_list_price boolean,
    is_removed boolean DEFAULT false NOT NULL,
    general_contract_date date,
    general_contract_number character varying(64),
    general_contract_stages character varying(64),
    items_number smallint DEFAULT 0 NOT NULL,
    publication_start_date date DEFAULT '1901-01-01'::date NOT NULL,
    is_lease_supplier_selection boolean,
    is_performance_indicator boolean,
    competitive_note_for_expert character varying(5000),
    expert_conclusion_id smallint,
    is_check_documentation boolean DEFAULT false NOT NULL,
    check_documentation_date timestamp without time zone,
    is_actual boolean DEFAULT true NOT NULL,
    savings_accounting_id smallint DEFAULT 0 NOT NULL,
    savings_sum_excluded_vat bigint,
    savings_sum_excluded_vat_rub bigint,
    savings_sum_included_vat bigint,
    savings_sum_included_vat_rub bigint,
    pricing_method_id smallint DEFAULT 0 NOT NULL,
    pricing_expert_id integer,
    pricing_organization_unit_id smallint DEFAULT 0 NOT NULL,
    pricing_resume character varying(1000),
    pricing_competitive_note_for_expert character varying(1000),
    is_pricing_by_complectation boolean DEFAULT false NOT NULL,
    pricing_vat_id smallint DEFAULT 0 NOT NULL,
    pricing_currency_id smallint,
    pricing_currency_rate bigint,
    pricing_sum_excluded_vat bigint DEFAULT 0 NOT NULL,
    pricing_sum_excluded_vat_rub bigint,
    pricing_sum_included_vat bigint,
    pricing_sum_included_vat_rub bigint,
    pricing_sum_vat bigint,
    pricing_sum_vat_rub bigint,
    pricing_transportation_vat_id smallint DEFAULT 0 NOT NULL,
    pricing_transportation_price bigint,
    pricing_transportation_price_rub bigint,
    pricing_transportation_sum_vat bigint,
    pricing_transportation_sum_vat_rub bigint,
    pricing_transportation_sum_included_vat bigint,
    pricing_transportation_sum_included_vat_rub bigint,
    pricing_total_sum bigint,
    pricing_total_sum_rub bigint,
    sum_vat_rub bigint DEFAULT 0 NOT NULL,
    budget_item_id smallint DEFAULT 0 NOT NULL,
    payment_balance_item_id smallint DEFAULT 0 NOT NULL,
    limit_on_construction bigint DEFAULT 0 NOT NULL,
    limit_on_works bigint DEFAULT 0 NOT NULL,
    priority smallint DEFAULT 0 NOT NULL,
    priority_income_contract_partner_text character varying(2000) DEFAULT ''::text NOT NULL,
    extract_number_d646 character varying(2000) DEFAULT ''::text NOT NULL,
    extract_date_d646 date DEFAULT '1901-01-01'::date NOT NULL,
    extract_sum_included_vat_rub_d646 bigint DEFAULT 0 NOT NULL,
    extract_number_d647 character varying(2000) DEFAULT ''::text NOT NULL,
    extract_date_d647 date DEFAULT '1901-01-01'::date NOT NULL,
    extract_sum_included_vat_rub_d647 bigint DEFAULT 0 NOT NULL,
    product_type_id smallint DEFAULT 0 NOT NULL,
    organizer_note character varying(2000) DEFAULT ''::text NOT NULL,
    description character varying(2000) DEFAULT ''::text NOT NULL,
    status_scheme_id smallint DEFAULT 0 NOT NULL,
    bid_opening_date date DEFAULT '1901-01-01'::date NOT NULL,
    single_supplier_note_for_expert character varying(2000) DEFAULT ''::text NOT NULL,
    control_pp_2013 smallint DEFAULT 0 NOT NULL,
    is_no_qualification boolean DEFAULT false NOT NULL,
    is_commission boolean DEFAULT false NOT NULL,
    is_priority_far_eastern boolean DEFAULT false NOT NULL,
    is_nko boolean DEFAULT false NOT NULL,
    is_priority_nonprofit boolean DEFAULT false NOT NULL,
    contract_sign_date date DEFAULT '1901-01-01'::date NOT NULL,
    active_uuid uuid,
    created_at timestamp without time zone NOT NULL,
    changed_at timestamp without time zone NOT NULL,
    created_by integer NOT NULL,
    changed_by integer NOT NULL,
    pricing_version smallint NOT NULL,
    pricing_started_at timestamp without time zone DEFAULT '1901-01-01 00:00:00'::timestamp without time zone NOT NULL,
    pricing_created_at timestamp without time zone DEFAULT '2024-12-23 00:00:00'::timestamp without time zone NOT NULL,
    pricing_changed_at timestamp without time zone DEFAULT '2024-12-23 00:00:00'::timestamp without time zone NOT NULL
);


ALTER TABLE ONLY public.plan_version
    ADD CONSTRAINT plan_version_pkey PRIMARY KEY (pricing_version, id);



