

CREATE TABLE public.plans_legacy
(
  uuid uuid NOT NULL PRIMARY KEY,
  id character varying(10) NOT NULL DEFAULT ''::character varying,
  is_actual BOOLEAN NOT NULL DEFAULT false,
  version_type SMALLINT NOT NULL DEFAULT 0,
  posting_date date NOT NULL DEFAULT '1900-01-01'::date,
  year SMALLINT NOT NULL DEFAULT 0,
  customer_id INTEGER NOT NULL DEFAULT 0,
  declarant_id INTEGER NOT NULL DEFAULT 0,
  agent_id INTEGER NOT NULL DEFAULT 0,
  initiator_user_id INTEGER NOT NULL DEFAULT 0,
  tender_user_id INTEGER NOT NULL DEFAULT 0,
  organizer_id INTEGER NOT NULL DEFAULT 0,
  section_id SMALLINT NOT NULL DEFAULT 0,
  contract_subject character varying(2000) NOT NULL DEFAULT ''::character varying,
  minimal_requirements character varying(2000) NOT NULL DEFAULT ''::character varying,
  customer_note character varying(1000) NOT NULL DEFAULT ''::character varying,
  number_customer character varying(40) NOT NULL DEFAULT ''::character varying,
  number_cgg character varying(64) NOT NULL DEFAULT ''::character varying,
  currency_id SMALLINT NOT NULL DEFAULT 0,
  currency_rate BIGINT NOT NULL DEFAULT 0,
  vat_id SMALLINT NOT NULL DEFAULT 0,
  sum_excluded_vat BIGINT NOT NULL DEFAULT 0,
  sum_vat BIGINT NOT NULL DEFAULT 0,
  sum_included_vat BIGINT NOT NULL DEFAULT 0,
  sum_excluded_vat_rub BIGINT NOT NULL DEFAULT 0,
  sum_vat_rub BIGINT NOT NULL DEFAULT 0,
  sum_included_vat_rub BIGINT NOT NULL DEFAULT 0,
  purchasing_method_id SMALLINT NOT NULL DEFAULT 0,
  purchasing_type_id SMALLINT NOT NULL DEFAULT 0,
  purchasing_kind_id SMALLINT NOT NULL DEFAULT 0,
  regulation_document_id SMALLINT NOT NULL DEFAULT 0,
  publication_type_id SMALLINT NOT NULL DEFAULT 0,
  master_system_id SMALLINT NOT NULL DEFAULT 0,
  funding_source_id SMALLINT NOT NULL DEFAULT 0,
  purchasing_trend_id SMALLINT NOT NULL DEFAULT 0,
  budget_item_id SMALLINT NOT NULL DEFAULT 0,
  payment_balance_item_id SMALLINT NOT NULL DEFAULT 0,
  is_smb BOOLEAN NOT NULL DEFAULT false,
  is_smb_sub BOOLEAN NOT NULL DEFAULT false,
  smb_exception_id SMALLINT NOT NULL DEFAULT 0,
  smb_sub_percent SMALLINT NOT NULL DEFAULT 0,
  smb_sub_sum BIGINT NOT NULL DEFAULT 0,
  documentation_date date NOT NULL DEFAULT '1900-01-01'::date,
  publication_date date NOT NULL DEFAULT '1900-01-01'::date,
  summing_up_date date NOT NULL DEFAULT '1900-01-01'::date,
  contract_sign_date date NOT NULL DEFAULT '1900-01-01'::date,
  delivery_start_date date NOT NULL DEFAULT '1900-01-01'::date,
  delivery_end_date date NOT NULL DEFAULT '1900-01-01'::date,
  supplier_id INTEGER NOT NULL DEFAULT 0,
  supplier_text character varying(255) NOT NULL DEFAULT ''::character varying,
  single_supplier_reason_id SMALLINT NOT NULL DEFAULT 0,
  single_supplier_expert_id INTEGER NOT NULL DEFAULT 0,
  single_supplier_decision_id SMALLINT NOT NULL DEFAULT 0,
  single_supplier_decision_resume character varying(5000) NOT NULL DEFAULT ''::character varying,
  is_affiliated BOOLEAN NOT NULL DEFAULT false,
  is_supplier_smb BOOLEAN NOT NULL DEFAULT false,
  is_commission BOOLEAN NOT NULL DEFAULT false,
  is_competitive_now BOOLEAN NOT NULL DEFAULT false,
  management_order_number character varying(30) NOT NULL DEFAULT ''::character varying,
  management_order_date date NOT NULL DEFAULT '1900-01-01'::date,
  reason_document character varying(30) NOT NULL DEFAULT ''::character varying,
  is_approved_by_d646 BOOLEAN NOT NULL DEFAULT false,
  is_price_analysis_by_d646 BOOLEAN NOT NULL DEFAULT false,
  is_approved_by_d647 BOOLEAN NOT NULL DEFAULT false,
  is_onm BOOLEAN NOT NULL DEFAULT false,
  is_agent_fee BOOLEAN NOT NULL DEFAULT false,
  agent_contract_number character varying(60) NOT NULL DEFAULT ''::character varying,
  is_design_stage BOOLEAN NOT NULL DEFAULT false,
  repair_stage_id SMALLINT NOT NULL DEFAULT 0,
  is_gas_supply BOOLEAN NOT NULL DEFAULT false,
  is_little_cost BOOLEAN NOT NULL DEFAULT false,
  is_banking_support BOOLEAN NOT NULL DEFAULT false,
  is_innovative BOOLEAN NOT NULL DEFAULT false,
  is_to_publish BOOLEAN NOT NULL DEFAULT false,
  rationale_for_not_publication character varying(1000) NOT NULL DEFAULT ''::character varying,
  rationale_for_publication character varying(1000) NOT NULL DEFAULT ''::character varying,
  is_cooperative BOOLEAN NOT NULL DEFAULT false,
  is_not_purchase BOOLEAN NOT NULL DEFAULT false,
  is_under_control BOOLEAN NOT NULL DEFAULT false,
  rationale_is_under_control character varying(1000) NOT NULL DEFAULT ''::character varying,
  technical_developer character varying(100) NOT NULL DEFAULT ''::character varying,
  limit_on_construction BIGINT NOT NULL DEFAULT 0,
  limit_on_works BIGINT NOT NULL DEFAULT 0,
  priority SMALLINT NOT NULL DEFAULT 0,
  is_priority_project BOOLEAN NOT NULL DEFAULT false,
  priority_project_document character varying(100) NOT NULL DEFAULT ''::character varying,
  is_priority_introductory BOOLEAN NOT NULL DEFAULT false,
  priority_introductory_date date NOT NULL DEFAULT '1900-01-01'::date,
  priority_introductory_document character varying(100) NOT NULL DEFAULT ''::character varying,
  is_priority_repair BOOLEAN NOT NULL DEFAULT false,
  priority_repair_document character varying(100) NOT NULL DEFAULT ''::character varying,
  is_priority_ozp BOOLEAN NOT NULL DEFAULT false,
  priority_ozp_document character varying(100) NOT NULL DEFAULT ''::character varying,
  is_priority_income_contract BOOLEAN NOT NULL DEFAULT false,
  priority_income_contract_document character varying(100) NOT NULL DEFAULT ''::character varying,
  priority_income_contract_partner_id INTEGER NOT NULL DEFAULT 0,
  priority_income_contract_partner_text character varying(100) NOT NULL DEFAULT ''::character varying,
  is_priority_other BOOLEAN NOT NULL DEFAULT false,
  is_headquarters BOOLEAN NOT NULL DEFAULT false,
  is_first_time BOOLEAN NOT NULL DEFAULT false,
  is_list_price BOOLEAN NOT NULL DEFAULT false,
  pricing_method_id SMALLINT NOT NULL DEFAULT 0,
  is_no_qualification BOOLEAN NOT NULL DEFAULT false,
  qualification_id INTEGER NOT NULL DEFAULT 0,
  extract_number_d646 character varying(40) NOT NULL DEFAULT ''::character varying,
  extract_date_d646 date NOT NULL DEFAULT '1900-01-01'::date,
  extract_sum_included_vat_rub_d646 BIGINT NOT NULL DEFAULT 0,
  extract_number_d647 character varying(40) NOT NULL DEFAULT ''::character varying,
  extract_date_d647 date NOT NULL DEFAULT '1900-01-01'::date,
  extract_sum_included_vat_rub_d647 BIGINT NOT NULL DEFAULT 0,
  product_type_id SMALLINT NOT NULL DEFAULT 0,
  organizer_note character varying(1000) NOT NULL DEFAULT ''::character varying,
  description character varying(40) NOT NULL DEFAULT 0,
  status_scheme_id SMALLINT NOT NULL DEFAULT 0,
  status_id SMALLINT NOT NULL DEFAULT 0,
  is_removed BOOLEAN NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT '1970-01-01 00:00:00'::timestamp without time zone,
  created_by INTEGER NOT NULL DEFAULT 0,
  changed_at timestamp without time zone NOT NULL DEFAULT '1970-01-01 00:00:00'::timestamp without time zone,
  changed_by INTEGER NOT NULL DEFAULT 0,
  commission_kind_id SMALLINT NOT NULL DEFAULT 0,
  version_number SMALLINT NOT NULL DEFAULT 0,
  general_contract_date date NOT NULL DEFAULT '1900-01-01'::date,
  general_contract_number character varying(64) NOT NULL DEFAULT ''::character varying,
  general_contract_stages character varying(64) NOT NULL DEFAULT ''::character varying,
  active_uuid uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
  items_number SMALLINT NOT NULL DEFAULT 0,
  publication_start_date date NOT NULL DEFAULT '1900-01-01'::date,
  is_lease_supplier_selection BOOLEAN NOT NULL DEFAULT false,
  is_pricing_by_complectation BOOLEAN NOT NULL DEFAULT false,
  bid_opening_date date NOT NULL DEFAULT '1900-01-01'::date,
  single_supplier_note_for_expert character varying(5000) NOT NULL DEFAULT ''::character varying,
  is_performance_indicator BOOLEAN NOT NULL DEFAULT false,
  competitive_note_for_expert character varying(5000) NOT NULL DEFAULT ''::character varying,
  control_pp_2013 SMALLINT DEFAULT 0
);
