UPDATE public.plan_version SET
is_smb                      = COALESCE(is_smb,                       FALSE),
is_smb_sub                  = COALESCE(is_smb_sub,                   FALSE),
is_affiliated               = COALESCE(is_affiliated,                FALSE),
is_supplier_smb             = COALESCE(is_supplier_smb,              FALSE),
is_competitive_now          = COALESCE(is_competitive_now,           FALSE),
is_price_analysis_by_d646   = COALESCE(is_price_analysis_by_d646,    FALSE),
is_approver_by_d647         = COALESCE(is_approver_by_d647,          FALSE),
is_onm                      = COALESCE(is_onm,                       FALSE),
is_agent_fee                = COALESCE(is_agent_fee,                 FALSE),
is_design_stage             = COALESCE(is_design_stage,              FALSE),
is_gas_supply               = COALESCE(is_gas_supply,                FALSE),
is_little_cost              = COALESCE(is_little_cost,               FALSE),
is_innovative               = COALESCE(is_innovative,                FALSE),
is_cooperative              = COALESCE(is_cooperative,               FALSE),
is_not_purchase             = COALESCE(is_not_purchase,              FALSE),
is_under_control            = COALESCE(is_under_control,             FALSE),
is_first_time               = COALESCE(is_first_time,                FALSE),
is_list_price               = COALESCE(is_list_price,                FALSE),
is_lease_supplier_selection = COALESCE(is_lease_supplier_selection,  FALSE),
is_performance_indicator    = COALESCE(is_performance_indicator,     FALSE);

ALTER TABLE public.plan_version
ALTER COLUMN is_smb                       SET DEFAULT FALSE,
ALTER COLUMN is_smb                       SET NOT NULL,
ALTER COLUMN is_smb_sub                   SET DEFAULT FALSE,
ALTER COLUMN is_smb_sub                   SET NOT NULL,
ALTER COLUMN is_affiliated                SET DEFAULT FALSE,
ALTER COLUMN is_affiliated                SET NOT NULL,
ALTER COLUMN is_supplier_smb              SET DEFAULT FALSE,
ALTER COLUMN is_supplier_smb              SET NOT NULL,
ALTER COLUMN is_competitive_now           SET DEFAULT FALSE,
ALTER COLUMN is_competitive_now           SET NOT NULL,
ALTER COLUMN is_price_analysis_by_d646    SET DEFAULT FALSE,
ALTER COLUMN is_price_analysis_by_d646    SET NOT NULL,
ALTER COLUMN is_approver_by_d647          SET DEFAULT FALSE,
ALTER COLUMN is_approver_by_d647          SET NOT NULL,
ALTER COLUMN is_onm                       SET DEFAULT FALSE,
ALTER COLUMN is_onm                       SET NOT NULL,
ALTER COLUMN is_agent_fee                 SET DEFAULT FALSE,
ALTER COLUMN is_agent_fee                 SET NOT NULL,
ALTER COLUMN is_design_stage              SET DEFAULT FALSE,
ALTER COLUMN is_design_stage              SET NOT NULL,
ALTER COLUMN is_gas_supply                SET DEFAULT FALSE,
ALTER COLUMN is_gas_supply                SET NOT NULL,
ALTER COLUMN is_little_cost               SET DEFAULT FALSE,
ALTER COLUMN is_little_cost               SET NOT NULL,
ALTER COLUMN is_innovative                SET DEFAULT FALSE,
ALTER COLUMN is_innovative                SET NOT NULL,
ALTER COLUMN is_cooperative               SET DEFAULT FALSE,
ALTER COLUMN is_cooperative               SET NOT NULL,
ALTER COLUMN is_not_purchase              SET DEFAULT FALSE,
ALTER COLUMN is_not_purchase              SET NOT NULL,
ALTER COLUMN is_under_control             SET DEFAULT FALSE,
ALTER COLUMN is_under_control             SET NOT NULL,
ALTER COLUMN is_first_time                SET DEFAULT FALSE,
ALTER COLUMN is_first_time                SET NOT NULL,
ALTER COLUMN is_list_price                SET DEFAULT FALSE,
ALTER COLUMN is_list_price                SET NOT NULL,
ALTER COLUMN is_lease_supplier_selection  SET DEFAULT FALSE,
ALTER COLUMN is_lease_supplier_selection  SET NOT NULL,
ALTER COLUMN is_performance_indicator     SET DEFAULT FALSE,
ALTER COLUMN is_performance_indicator     SET NOT NULL;
