//! Позиции ППЗ, но уже по логике АСЕЗ-2.0
use asez2_shared_db::db_item::{AsezDate, AsezTimestamp, DbUpsert};
use asez2_shared_db::db_item::{DbItemExt, DbVersioned};
use asez2_shared_db::{DbAdaptor, DbItem};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::maths::*;
use crate::ContractAmendmentItemKindId;

/// Позиции ППЗ, но уже по логике АСЕЗ-2.0
#[derive(
    Debug,
    Default,
    Clone,
    PartialEq,
    DbItem,
    DbItemExt,
    DbAdaptor,
    DbVersioned,
    DbUpsert,
)]
#[adaptor_derive(Debug, Default, Clone, PartialEq, Serialize, Deserialize)]
#[item_table = "contract_amendment_item"]
#[db_version_table = "contract_amendment_item_version"]
#[item_aggr_insert]
#[adaptor_fields_with_values]
pub struct ContractAmendmentItem {
    #[item_field_pkey]
    pub uuid: Uuid,
    pub id: i64,
    pub header_uuid: Uuid,
    pub number: i16,
    pub active_uuid: Uuid,
    pub source_uuid: Uuid,
    pub description_internal: String,
    pub description_external: String,
    pub product_type_id: i16,
    pub kind_id: ContractAmendmentItemKindId,
    pub category_id: i16,
    pub budget_item_id: i16,
    pub payment_balance_item_id: i16,
    pub investment_project_id: i32,
    pub okpd2_id: i32,
    pub okved2_id: i16,
    pub okato_id: i32,
    pub is_not_russian_delivery: bool,
    pub delivery_basis: String,
    pub consumer_id: i32,
    pub quantity: Quantity,
    pub unit_id: i16,
    pub price: CurrencyValue,
    pub price_unit: i16,
    pub vat_id: VatId,
    pub sum_excluded_vat: CurrencyValue,
    pub sum_vat: CurrencyValue,
    pub sum_included_vat: CurrencyValue,
    pub currency_id: i16,
    pub currency_rate: CurrencyRate,
    pub currency_rate_date: AsezDate,
    pub sum_excluded_vat_rub: CurrencyValue,
    pub sum_vat_rub: CurrencyValue,
    pub sum_included_vat_rub: CurrencyValue,
    pub delivery_start_date: AsezDate,
    pub delivery_end_date: AsezDate,
    pub initial_quantity: Quantity,
    pub initial_unit_id: i16,
    pub initial_price: CurrencyValue,
    pub initial_price_unit: i32,
    pub initial_vat_id: VatId,
    pub initial_sum_excluded_vat: CurrencyValue,
    pub initial_sum_vat: CurrencyValue,
    pub initial_sum_included_vat: CurrencyValue,
    pub initial_currency_id: i16,
    pub initial_currency_rate: CurrencyRate,
    pub initial_currency_rate_date: AsezDate,
    pub initial_sum_excluded_vat_rub: CurrencyValue,
    pub initial_sum_vat_rub: CurrencyValue,
    pub initial_sum_included_vat_rub: CurrencyValue,
    pub initial_delivery_start_date: AsezDate,
    pub initial_delivery_end_date: AsezDate,
    pub previous_quantity: Quantity,
    pub previous_unit_id: i16,
    pub previous_price: CurrencyValue,
    pub previous_price_unit: i32,
    pub previous_vat_id: VatId,
    pub previous_sum_excluded_vat: CurrencyValue,
    pub previous_sum_vat: CurrencyValue,
    pub previous_sum_included_vat: CurrencyValue,
    pub previous_currency_id: i16,
    pub previous_currency_rate: CurrencyRate,
    pub previous_currency_rate_date: AsezDate,
    pub previous_sum_excluded_vat_rub: CurrencyValue,
    pub previous_sum_vat_rub: CurrencyValue,
    pub previous_sum_included_vat_rub: CurrencyValue,
    pub previous_delivery_start_date: AsezDate,
    pub previous_delivery_end_date: AsezDate,
    pub material_code_local: String,
    pub material_code_ius_mtr: String,
    pub is_serial: bool,
    pub pzp_code: String,
    pub nomenclature_group_id: i16,
    pub source_country_id: i16,
    pub producer_country_id: i16,
    pub producer_id: i32,
    pub is_dealer: bool,
    pub repair_summary_code: String,
    pub repair_inventory_number: String,
    pub repair_text: String,
    pub repair_plan_code: String,
    pub is_material_registry: bool,
    pub certificate_holder_id: i32,
    pub certificate_holder_text: String,
    pub certificate_text: String,
    pub certificate_number: String,
    pub is_removed: bool,
    //новые поля
    pub delta_quantity: Option<Quantity>,
    pub delta_price: Option<CurrencyValue>,
    pub delta_price_rub: Option<CurrencyValue>,
    pub delta_sum_vat: Option<CurrencyValue>,
    pub delta_sum_vat_rub: Option<CurrencyValue>,
    pub delta_sum_excluded_vat: Option<CurrencyValue>,
    pub delta_sum_excluded_vat_rub: Option<CurrencyValue>,
    pub delta_sum_included_vat: Option<CurrencyValue>,
    pub delta_sum_included_vat_rub: Option<CurrencyValue>,
    pub uuid_item_proposal: Option<i64>,

    // pricing
    pub pricing_quantity: Quantity,
    pub pricing_unit_id: i16,
    pub pricing_price: CurrencyValue,
    pub pricing_price_rub: Option<CurrencyValue>,

    pub pricing_department_id: i32,
    pub pricing_expert_id: i32,
    pub pricing_method_id: i16,
    pub pricing_resume: String,

    pub pricing_vat_id: VatId,
    pub pricing_currency_id: i16,
    pub pricing_currency_rate: Option<CurrencyRate>,
    pub pricing_currency_rate_date: Option<AsezDate>,
    pub pricing_sum_excluded_vat: Option<CurrencyValue>,
    pub pricing_sum_excluded_vat_rub: Option<CurrencyValue>,
    pub pricing_sum_included_vat: Option<CurrencyValue>,
    pub pricing_sum_included_vat_rub: Option<CurrencyValue>,
    pub pricing_sum_vat: Option<CurrencyValue>,
    pub pricing_sum_vat_rub: Option<CurrencyValue>,
    pub pricing_transportation_vat_id: VatId,
    pub pricing_transportation_price: CurrencyValue,
    pub pricing_transportation_price_rub: Option<CurrencyValue>,
    pub pricing_transportation_sum_vat: Option<CurrencyValue>,
    pub pricing_transportation_sum_vat_rub: Option<CurrencyValue>,
    pub pricing_transportation_sum_included_vat: Option<CurrencyValue>,
    pub pricing_transportation_sum_included_vat_rub: Option<CurrencyValue>,
    pub pricing_total_sum: Option<CurrencyValue>,
    pub pricing_total_sum_rub: Option<CurrencyValue>,

    pub pricing_delta_unit_id: Option<i64>,
    pub pricing_delta_quantity: Option<Quantity>,
    pub pricing_delta_currency_id: Option<i64>,
    pub pricing_delta_currency_rate: Option<CurrencyRate>,
    pub pricing_delta_currency_rate_date: Option<AsezDate>,
    pub pricing_delta_price: Option<CurrencyValue>,
    pub pricing_delta_price_rub: Option<CurrencyValue>,
    pub pricing_delta_sum_excluded_vat: Option<CurrencyValue>,
    pub pricing_delta_sum_excluded_vat_rub: Option<CurrencyValue>,
    pub pricing_delta_sum_vat: Option<CurrencyValue>,
    pub pricing_delta_sum_vat_rub: Option<CurrencyValue>,
    pub pricing_delta_sum_included_vat: Option<CurrencyValue>,
    pub pricing_delta_sum_included_vat_rub: Option<CurrencyValue>,
    pub pricing_delta_transportation_price: Option<CurrencyValue>,
    pub pricing_delta_transportation_price_rub: Option<CurrencyValue>,
    pub pricing_delta_transportation_sum_vat: Option<CurrencyValue>,
    pub pricing_delta_transportation_sum_vat_rub: Option<CurrencyValue>,
    pub pricing_delta_transportation_sum_included_vat: Option<CurrencyValue>,
    pub pricing_delta_transportation_sum_included_vat_rub: Option<CurrencyValue>,
    pub pricing_delta_total_sum: Option<CurrencyValue>,
    pub pricing_delta_total_sum_rub: Option<CurrencyValue>,

    // created & changed
    pub created_at: AsezTimestamp,
    pub changed_at: AsezTimestamp,
    pub created_by: i32,
    pub changed_by: i32,
    /// When the current version was created at.
    pub pricing_created_at: AsezTimestamp,
    /// When the version was last updated from an external source.
    pub pricing_changed_at: AsezTimestamp,
}
