//! This is used in processing for tracking changes to fields.

use serde::{Deserialize, Serialize};
use sqlx::Type;
use uuid::Uuid;

use asez2_shared_db::db_item::{
    AsezTimestamp, DbAdaptor, DbItem, DbUpdateByFilter, Filter,
};
use asez2_shared_db::value::Value;
use shared_db_derive::DbEnum;

use crate::StatusHistory;

#[derive(Debug, Default, Clone, DbItem, DbAdaptor, PartialEq)]
#[adaptor_derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
#[item_table = "field_history"]
#[item_manually_activate_fields]
#[item_aggr_insert]
pub struct FieldChange {
    #[item_field_pkey]
    #[item_field_autogen]
    pub id: i64, // For now it's a pain to work with autogenerated ids, so we use normal uuids.
    pub record_uuid: Uuid,
    pub table_name: String,
    pub field_name: String,
    /// TODO: See if we need to strip the `sqlx::types::Json` layer for the FieldChangeRep DTO...
    pub field_value: Option<sqlx::types::Json<Value>>, // can actually be json in sqlx
    pub record_status: HistoryStatus,
    pub created_by: i32,
    #[item_field_activate_with = "AsezTimestamp::now()"]
    pub created_at: AsezTimestamp,
}
impl DbUpdateByFilter for FieldChange {}

pub const RECORD_STATUS: &str = "record_status";

impl FieldChange {
    fn activate_fields_manually(&mut self) {
        self.record_status = HistoryStatus::Proposed;
    }

    pub fn as_status_history(
        &self,
        status_field: &str,
        comment: &str,
    ) -> Option<StatusHistory> {
        let value = self.field_value.as_ref()?;

        match (self.field_name == status_field, &value.0) {
            (true, Value::Int(status_id)) => Some(StatusHistory {
                uuid: Uuid::new_v4(),
                object_uuid: self.record_uuid,
                status_id: *status_id as i16,
                comment: comment.to_owned(),
                created_at: self.created_at,
                created_by: self.created_by,
            }),
            _ => None,
        }
    }

    // Used for more efficiently changing the status of a large number of records.
    pub async fn mass_update_status(
        ids: &[Self],
        new_status: HistoryStatus,
        pool: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    ) -> Result<(), asez2_shared_db::result::SharedDbError> {
        for ids in ids.chunks(asez2_shared_db::db_item::UPDATE_UNNEST_VALUES) {
            let ids = ids.iter().map(|x| x.id);
            let filter = Filter::in_any(Self::id, ids).into();

            Self {
                record_status: new_status,
                ..Self::default()
            }
            .update_by_filter(&[Self::record_status], &filter, &mut *pool)
            .await?;
        }
        Ok(())
    }
}

/// History can have one of several status.
/// This allows us to track whether a record was changed successfully,
/// and if not, at which point the failure occurred.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, DbEnum, Type)]
#[repr(i16)]
pub enum HistoryStatus {
    #[db_default]
    Proposed = 1,
    Checked = 2,
    BackedUp = 3,
    Finished = 4,
}
