[package]
name = "http-middleware"
version = "0.0.1"
edition = "2021"

# See: https://doc.rust-lang.org/cargo/reference/manifest.html
# NB: Dependencies should be as broad based as possible, however we must be
# careful due to the limitation of:
# a) Using an older compiler.
# b) Using a limited registry.
[dependencies]
# local
igg-tracing = { path = "../igg-tracing" }
rabbit-services = { path = "../rabbit-services", features = ["view-storage"] }
shared-essential = { path = "../shared-essential" }

# foregin 
actix-http.workspace = true
actix-web.workspace = true
actix-session.workspace = true
tracing-actix-web.workspace = true
amqprs.workspace = true
base64.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
reqwest.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
