-- Table: public.protocol_status
CREATE TABLE public.protocol_status (
  id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 100 START 600 MINVALUE 600 NO MAXVALUE CACHE 1
  ),
  protocol_type_id SMALLINT NOT NULL,
  name VARCHAR(250) NOT NULL DEFAULT '',
  is_removed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_by INTEGER NOT NULL,
  changed_by INTEGER NOT NULL,
  PRIMARY KEY (id, protocol_type_id),
  FOREIGN KEY (protocol_type_id) REFERENCES public.protocol_type(id) ON DELETE CASCADE
);

COMMENT ON TABLE public.protocol_status IS 'Справочник "Статусы Протокола"';

COMMENT ON COLUMN public.protocol_status.id IS 'Значения: Протокол очного/заочного заседания СК:
100 - Сформирован
200 - На согласовании
300 - На подписании
400 - Утвержден
500 - Удален';

COMMENT ON COLUMN public.protocol_status.protocol_type_id IS 'Справочник «Тип Протокола»:
1 - Протокол очного заседания СК
2 - Протокол заочного заседания СК';

COMMENT ON COLUMN public.protocol_status.is_removed IS 'Признак удаления записи';

COMMENT ON COLUMN public.protocol_status.name IS 'Наименование статуса
100 - Сформирован
200 - На согласовании
300 - На подписании
400 - Утвержден
500 - Удален';

COMMENT ON COLUMN public.protocol_status.changed_at IS 'Дата и время изменения. Автоматически присваивается при создании объекта';

COMMENT ON COLUMN public.protocol_status.created_at IS 'Дата и время создания. Автоматически присваивается при создании объекта';

COMMENT ON COLUMN public.protocol_status.changed_by IS 'Код пользователя ответственного исполнителя, изменившего объект';

COMMENT ON COLUMN public.protocol_status.created_by IS 'Код пользователя ответственного исполнителя, создавшего объект';

INSERT INTO protocol_status(id, protocol_type_id, name, created_at, changed_at, created_by, changed_by)
VALUES
    (100, 1, 'Сформирован', now(), now(), 1, 1),
    (200, 1, 'На согласовании', now(), now(), 1, 1),
    (300, 1, 'На подписании', now(), now(), 1, 1),
    (400, 1, 'Утвержден', now(), now(), 1, 1),
    (500, 1, 'Удален', now(), now(), 1, 1),
    (100, 2, 'Сформирован', now(), now(), 1, 1),
    (200, 2, 'На согласовании', now(), now(), 1, 1),
    (300, 2, 'На подписании', now(), now(), 1, 1),
    (400, 2, 'Утвержден', now(), now(), 1, 1),
    (500, 2, 'Удален', now(), now(), 1, 1)
;
