-- Table: public.agenda_status
CREATE TABLE public.agenda_status (
  id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 100 START 100 MINVALUE 100 NO MAXVALUE CACHE 1
  ) PRIMARY KEY,
  name VARCHAR(250) NOT NULL DEFAULT '',
  is_removed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_by INTEGER NOT NULL,
  changed_by INTEGER NOT NULL
);

COMMENT ON TABLE public.agenda_status IS 'Справочник "Статусы Повестки"';

COMMENT ON COLUMN public.agenda_status.id IS 'Значения:
100 - Сформирована
200 - Отправлена
300 - Сформирован Протокол
400 - Удалена';

COMMENT ON COLUMN public.agenda_status.name IS 'Наименование статуса
100 - Сформирована
200 - Отправлена
300 - Сформирован Протокол
400 - Удалена';

COMMENT ON COLUMN public.agenda_status.is_removed IS 'Признак удаления записи';

COMMENT ON COLUMN public.agenda_status.changed_at IS 'Дата и время изменения. Автоматически присваивается при создании объекта';
COMMENT ON COLUMN public.agenda_status.created_at IS 'Дата и время создания. Автоматически присваивается при создании объекта';
COMMENT ON COLUMN public.agenda_status.changed_by IS 'Код пользователя ответственного исполнителя, изменившего объект';
COMMENT ON COLUMN public.agenda_status.created_by IS 'Код пользователя ответственного исполнителя, создавшего объект';

INSERT INTO
  public.agenda_status(name, changed_at, created_at, changed_by, created_by)
VALUES
  ('Сформирована', now(), now(), 1, 1),
  ('Отправлена', now(), now(), 1, 1),
  ('Сформирован Протокол', now(), now(), 1, 1),
  ('Удалена', now(), now(), 1, 1)
;
