use std::{path::Path, sync::Arc};

use asez2_shared_db::result::SharedDbError;
use sqlx::PgPool;

use crate::{
    db::{apply_sql, prepare_for_test},
    id_pool::FreeId,
};

/// Test harness object that can be obtained for testing purposes (possibly with
/// some additional data as argument) and then finalized to release resources,
/// if any.
#[async_trait::async_trait]
pub trait TestHarness: Sized {
    type Error;
    type Arg;

    /// Creates a new instance using defaults.
    async fn initialize() -> Result<Self, Self::Error>;

    /// Creates a new instance using specified argument.
    async fn initialize_with(arg: Self::Arg) -> Result<Self, Self::Error>;
}

/// Test Postgress pool.
///
/// This pool ensures that
/// * tests executed in parallel are using different databases
/// * when first test is started, database is prepared by removing all data
///   and applying all migrations specidied in crate's `migrations` directory,
///   and also names of all empty tables are stored for later.
/// * before each next test is started, all empty tables are TRUNCATEd
/// * with argument (str), its content is used to apply a test fixture before test execution.
///
/// Note that connection established by the the underlying `PgPool` may leak,
/// so the pool should be either closed manually, or reused across tests.
pub struct TestDbPool {
    pool: Arc<PgPool>,
    _id: FreeId,
}

impl TestDbPool {
    pub async fn new() -> Result<Self, SharedDbError> {
        let (pool, _id) = prepare_for_test(Some(Path::new("migrations"))).await?;

        Ok(TestDbPool { pool, _id })
    }

    pub async fn apply_fixture(
        &self,
        fixture: &'static str,
    ) -> Result<(), TestDbError> {
        apply_sql(&self.pool, fixture).await
    }
}

/// Type for DB connection pool.
pub type DbPool = PgPool;

/// Error generated by DB connection pool initialization.
pub type TestDbError = SharedDbError;

#[async_trait::async_trait]
impl TestHarness for TestDbPool {
    type Error = TestDbError;
    type Arg = &'static str;

    async fn initialize() -> Result<Self, Self::Error> {
        TestDbPool::new().await
    }

    async fn initialize_with(fixture: &'static str) -> Result<Self, Self::Error> {
        let this = TestDbPool::new().await?;
        this.apply_fixture(fixture).await?;
        Ok(this)
    }
}

impl std::ops::Deref for TestDbPool {
    type Target = Arc<PgPool>;

    fn deref(&self) -> &Self::Target {
        &self.pool
    }
}

#[macro_export]
macro_rules! test_db_pool {
    ($name:ident, $fixture:expr) => {
        struct $name($crate::harness::TestDbPool);

        #[async_trait::async_trait]
        impl $crate::harness::TestHarness for $name {
            type Error = $crate::harness::TestDbError;
            type Arg = &'static str;

            async fn initialize() -> Result<Self, Self::Error> {
                let this = $crate::harness::TestDbPool::new().await?;
                this.apply_fixture($fixture).await?;
                Ok($name(this))
            }

            async fn initialize_with(
                fixture: &'static str,
            ) -> Result<Self, Self::Error> {
                let this = $crate::harness::TestDbPool::new().await?;
                this.apply_fixture(fixture).await?;
                Ok($name(this))
            }
        }

        impl std::ops::Deref for $name {
            type Target = std::sync::Arc<$crate::harness::DbPool>;

            fn deref(&self) -> &Self::Target {
                self.0.deref()
            }
        }
    };
}
